version: '3'
services:
  db:
    container_name: node_db
    image: mongo:latest
    environment:
      - MONGODB_USER="root" 
      - MONGODB_PASS="root"
    volumes:
      - /var/lib/mysql 
    ports:
      - 27017:27017